config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :albums do 
    resources :songs
  end
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
    render :index
  end

  def new
    @albums = Album.new
    render :new 
  end

  def create
    @albums = Album.new(album_params)
    if @album.save
      redirect_to albums_path
    else
      render :new
    end
  end


  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album= Album.find(params[:id])
    if @album.update(album_params)
      redirect_to albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end

  private
  def album_params
    params.require(:album).permit(:name, :genre)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @album = Album.find(params[:album_id])
    @song = @album.songs.new
    render :new
end

  def create
  @album = Album.find(params[:album_id])
  @song = @album.songs.new(song_params)
  if @song.save
    redirect_to album_path(@album)
  else
    render :new
  end
end

def show
  @album = Album.find(params[:album_id])
  @song = Song.find(params[:id])
  render :show
end

def edit
  @album = Album.find(params[:album_id])
  @song = Song.find(params[:id])
  render :edit
end

def update
  @song = Song.find(params[:id])
  if @song.update(song_params)
    redirect_to album_path(@song.album)
  else
    @album = Album.find(params[:album_id])
    render :edit
  end
end

def destroy
  @song = Song.find(params[:id])
  @song.destroy
  redirect_to album_path(@song.album)
end

private
  def song_params
    params.require(:song).permit(:name, :lyrics)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/albums/edit.html.erb
<h1>Edit album</h1>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit  %>
<% end %>

app/views/layouts/albums/index.html.erb
<h1>Albums</h1>

<% if @albums.any? %>
  <ul>
    <% @albums.each do |album| %>
      <li><%= link_to album.name, album_path(album) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no albums yet.</p>
<% end %>


<%= button_to "Create new album", 
              new_album_path,
              method: :get %>

app/views/layouts/albums/new.html.erb
<h1>New album</h1>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit  %>
<% end %>

app/views/layouts/albums/show.html.erb
<h1><%= @album.name %></h1>
<h3><%= @album.genre %></h3>

<% if @album.songs.any? %>
  <h4>Here are the songs for this album:</h4>

  <% @album.songs.each do |song| %>
    <ul>
      <li>
        <%= link_to song.name, album_song_path(@album, song) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No songs are listed for this album.</p>
<% end %>

<%= button_to "Add Song to Album", 
              new_album_song_path(@album),
              method: :get %>

<%= button_to "Edit Album", 
              edit_album_path(@album),
              method: :get %>

<%= button_to "Delete Album", 
              album_path(@album),
              method: :delete %>                 

<%= button_to "Return to Albums Page", 
              albums_path,
              method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecordStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Edit song:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/new.html.erb
<h1>Add a new song:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/show.html.erb
<h1>Song: <%= @song.name %></h1>
<h2>Album: <%= @album.name %></h2>
<h3><%= @song.lyrics %></h3>

<%= button_to "Edit song", 
              edit_album_song_path(@album, @song), 
              method: :get %>

<%= button_to "Delete Song", 
              album_song_path(@album, @song),
              method: :delete %>

<%= button_to "Return to album", 
              album_path(@album), 
              method: :get %>